name: widgetly
description: "A collection of customizable Flutter widgets designed for rapid UI development. Widgetly provides ready-to-use components with consistent styling and behavior."
version: 0.0.13
homepage: https://github.com/aprizzo/widgetly
repository: https://github.com/aprizzo/widgetly
documentation: https://github.com/aprizzo/widgetly/blob/main/README.md

# Add these tags
topics:
  - widgets
  - ui
  - components
  - flutter-widgets
  - customizable

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  keyboard_actions: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
